sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 8
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - yarn global add codecov
script:
  - yarn validate
after_success:
  - codecov
